export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_PRODUCTS_DATA: "GET_PRODUCTS_DATA",
  CHANGE_ID: "CHANGE_ID",
  MODAL: "MODAL",
  AUTH_OFFLINE: "AUTH_OFFLINE",
};


export const JSON_API_USERS = "http://localhost:8000/users";
export const PRODUCTS_API = "http://localhost:8000/products";


  // REACT_APP_FIREBASE_KEY = "1:887906957622:web:0c89e4c8cc06f744d7db97",
  // REACT_APP_FIREBASE_KEY = "G-W3PQJ5Q5NS"